Repository Java-Discord/JavaBot, pull requests merged in 2021-12, with the labels that each got.

#131 Fixed Message not being sent to Banned users & added reference to unban form
  src/main/java/com/javadiscord/javabot/commands/staff_commands/Ban.java
  src/main/java/com/javadiscord/javabot/data/properties/config/guild/ModerationConfig.java
Labels: enhancement, bug fix, review requested

#139 Added Regex Command (#136)
  src/main/java/com/javadiscord/javabot/commands/user_commands/Regex.java
  src/main/resources/commands.yaml
Labels: review requested, new feature

#141 Added Info Message for Dormant Help Channels
  src/main/java/com/javadiscord/javabot/data/properties/config/guild/HelpConfig.java
  src/main/java/com/javadiscord/javabot/service/help/HelpChannelManager.java
Labels: enhancement, feature: help-system

#140 Removed `/help` & split commands.yaml into multiple files
  src/main/java/com/javadiscord/javabot/Constants.java
  src/main/java/com/javadiscord/javabot/commands/SlashCommandHandler.java
  src/main/java/com/javadiscord/javabot/commands/SlashCommands.java
  src/main/java/com/javadiscord/javabot/commands/user_commands/Help.java
  src/main/java/com/javadiscord/javabot/service/PresenceUpdater.java
  src/main/java/com/javadiscord/javabot/service/help/HelpGuidelinesCommandHandler.java
  src/main/resources/commands.yaml
  src/main/resources/commands/economy.yaml
  src/main/resources/commands/help.yaml
  src/main/resources/commands/jam.yaml
  src/main/resources/commands/qotw.yaml
  src/main/resources/commands/staff.yaml
  src/main/resources/commands/user.yaml
  src/main/resources/help-guidelines.txt
  src/main/resources/staff/commands.yaml
Labels: enhancement

#143 Added Support for `Choice` Option Types
  src/main/java/com/javadiscord/javabot/data/properties/command/OptionChoiceConfig.java
  src/main/java/com/javadiscord/javabot/data/properties/command/OptionConfig.java
Labels: enhancement

#145 Introduction of `ModerationService` & Warn Severity
  src/main/java/net/javadiscord/javabot/data/config/guild/ModerationConfig.java
  src/main/java/net/javadiscord/javabot/data/h2db/DbHelper.java
  src/main/java/net/javadiscord/javabot/events/InteractionListener.java
  src/main/java/net/javadiscord/javabot/systems/commands/ProfileCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/AutoMod.java
  src/main/java/net/javadiscord/javabot/systems/moderation/BanCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/ClearWarnsCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/KickCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/ModerationService.java
  src/main/java/net/javadiscord/javabot/systems/moderation/MuteCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/MutelistCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/UnbanCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/UnmuteCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/WarnCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/WarnsCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/WarnCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/WarnsCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/dao/WarnRepository.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/model/Warn.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/model/WarnSeverity.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/subcommands/DiscardAllWarnsSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/subcommands/DiscardWarnByIdSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/subcommands/WarnAddSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/ClearQOTWCommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/CorrectCommand.java
  src/main/resources/commands/staff.yaml
  src/main/resources/migrations/12-20-2021_add_warn_table.sql
  src/main/resources/schema.sql
Labels: enhancement

#147 Added `/db-admin export-table` Subcommand
  src/main/java/net/javadiscord/javabot/data/h2db/commands/DbAdminCommandHandler.java
  src/main/java/net/javadiscord/javabot/data/h2db/commands/ExportTableSubcommand.java
  src/main/java/net/javadiscord/javabot/data/h2db/commands/MigrateSubcommand.java
  src/main/resources/commands/staff.yaml
Labels: enhancement

#137 Added `/search` command and automatic scam link detection
  src/main/java/net/javadiscord/javabot/data/config/SystemsConfig.java
  src/main/java/net/javadiscord/javabot/systems/commands/LmgtfyCommand.java
  src/main/java/net/javadiscord/javabot/systems/commands/SearchCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/AutoMod.java
  src/main/resources/commands/user.yaml
  src/main/resources/spamLinks.txt
Labels: changes required, new feature

#150 Cleaned up `SuggestionListener`
  src/main/java/net/javadiscord/javabot/events/SuggestionListener.java
Labels: enhancement
