Repository Java-Discord/JavaBot, pull requests merged in 2021-10, with the labels that each got.

#81 Some Cleanup
  src/main/java/com/javadiscord/javabot/PresenceUpdater.java
  src/main/java/com/javadiscord/javabot/SlashCommands.java
  src/main/java/com/javadiscord/javabot/commands/custom_commands/CustomCommandList.java
  src/main/java/com/javadiscord/javabot/commands/custom_commands/CustomCommands.java
  src/main/java/com/javadiscord/javabot/commands/moderation/Ban.java
  src/main/java/com/javadiscord/javabot/commands/moderation/ClearWarns.java
  src/main/java/com/javadiscord/javabot/commands/moderation/Embed.java
  src/main/java/com/javadiscord/javabot/commands/moderation/Kick.java
  src/main/java/com/javadiscord/javabot/commands/moderation/Mute.java
  src/main/java/com/javadiscord/javabot/commands/moderation/Mutelist.java
  src/main/java/com/javadiscord/javabot/commands/moderation/Report.java
  src/main/java/com/javadiscord/javabot/commands/moderation/Unban.java
  src/main/java/com/javadiscord/javabot/commands/moderation/Unmute.java
  src/main/java/com/javadiscord/javabot/commands/moderation/Warn.java
  src/main/java/com/javadiscord/javabot/commands/moderation/Warns.java
  src/main/java/com/javadiscord/javabot/commands/other/Question.java
  src/main/java/com/javadiscord/javabot/commands/other/Version.java
  src/main/java/com/javadiscord/javabot/commands/other/qotw/ClearQOTW.java
  src/main/java/com/javadiscord/javabot/commands/other/qotw/Correct.java
  src/main/java/com/javadiscord/javabot/commands/other/qotw/Leaderboard.java
  src/main/java/com/javadiscord/javabot/commands/other/suggestions/Accept.java
  src/main/java/com/javadiscord/javabot/commands/other/suggestions/Clear.java
  src/main/java/com/javadiscord/javabot/commands/other/suggestions/Decline.java
  src/main/java/com/javadiscord/javabot/commands/reaction_roles/ReactionRoles.java
  src/main/java/com/javadiscord/javabot/commands/reaction_roles/subcommands/CreateReactionRole.java
  src/main/java/com/javadiscord/javabot/commands/reaction_roles/subcommands/DeleteReactionRole.java
  src/main/java/com/javadiscord/javabot/commands/reaction_roles/subcommands/ListReactionRoles.java
  src/main/java/com/javadiscord/javabot/commands/user_commands/Avatar.java
  src/main/java/com/javadiscord/javabot/commands/user_commands/BotInfo.java
  src/main/java/com/javadiscord/javabot/commands/user_commands/ChangeMyMind.java
  src/main/java/com/javadiscord/javabot/commands/user_commands/Help.java
  src/main/java/com/javadiscord/javabot/commands/user_commands/IDCalc.java
  src/main/java/com/javadiscord/javabot/commands/user_commands/Ping.java
  src/main/java/com/javadiscord/javabot/commands/user_commands/Profile.java
  src/main/java/com/javadiscord/javabot/commands/user_commands/ServerInfo.java
  src/main/java/com/javadiscord/javabot/commands/user_commands/Uptime.java
  src/main/java/com/javadiscord/javabot/events/AutoMod.java
  src/main/java/com/javadiscord/javabot/events/StarboardListener.java
  src/main/java/com/javadiscord/javabot/events/Startup.java
  src/main/java/com/javadiscord/javabot/events/SubmissionListener.java
  src/main/java/com/javadiscord/javabot/events/SuggestionListener.java
  src/main/java/com/javadiscord/javabot/other/Colors.java
  src/main/java/com/javadiscord/javabot/other/Constants.java
  src/main/java/com/javadiscord/javabot/other/Database.java
  src/main/java/com/javadiscord/javabot/other/Misc.java
  src/main/java/com/javadiscord/javabot/other/ServerLock.java
  src/main/java/com/javadiscord/javabot/other/StatsCategory.java
  src/main/java/com/javadiscord/javabot/properties/config/GuildConfig.java
  src/main/java/com/javadiscord/javabot/properties/config/guild/EmoteConfig.java
  src/main/java/com/javadiscord/javabot/properties/config/guild/SlashCommandConfig.java
  src/main/resources/textfiles/startup.txt
Labels: Enhancement

#82 Updated help channel system to use open and reserved categories instead of names
  src/main/java/com/javadiscord/javabot/help/AlphabetNamingStrategy.java
  src/main/java/com/javadiscord/javabot/help/AnimalNamingStrategy.java
  src/main/java/com/javadiscord/javabot/help/HelpChannelListener.java
  src/main/java/com/javadiscord/javabot/help/HelpChannelManager.java
  src/main/java/com/javadiscord/javabot/help/HelpChannelUpdater.java
  src/main/java/com/javadiscord/javabot/help/UnreserveCommandHandler.java
  src/main/java/com/javadiscord/javabot/properties/config/guild/HelpConfig.java
  src/main/resources/migrations/02-10-2021_add_reserved_help_channels.sql
Labels: Enhancement

#85 added `.sync()` method
  src/main/java/com/javadiscord/javabot/help/HelpChannelManager.java
  src/main/java/com/javadiscord/javabot/help/HelpChannelUpdater.java
Labels: Enhancement, Help-System

#88 Moved Stats Category updates to a scheduled Thread pool
  src/main/java/com/javadiscord/javabot/Bot.java
  src/main/java/com/javadiscord/javabot/StatsUpdater.java
  src/main/java/com/javadiscord/javabot/events/Startup.java
  src/main/java/com/javadiscord/javabot/events/UserJoin.java
  src/main/java/com/javadiscord/javabot/events/UserLeave.java
  src/main/java/com/javadiscord/javabot/other/StatsCategory.java
  src/main/java/com/javadiscord/javabot/properties/config/guild/StatsConfig.java
Labels: enhancement

#91 Updated Help Channels (again)
  src/main/java/com/javadiscord/javabot/events/UserLeave.java
  src/main/java/com/javadiscord/javabot/help/HelpChannelListener.java
Labels: enhancement, feature: help-system

#89 Refactor auto-mod
  src/main/java/com/javadiscord/javabot/events/AutoMod.java
Labels: changes required, enhancement
