Repository Java-Discord/JavaBot, pull requests merged in 2022-02, with the labels that each got.

#205 Added basic Job Channel Vote Functionality
  src/main/java/net/javadiscord/javabot/Bot.java
  src/main/java/net/javadiscord/javabot/data/config/guild/EmoteConfig.java
  src/main/java/net/javadiscord/javabot/data/config/guild/ModerationConfig.java
  src/main/java/net/javadiscord/javabot/events/JobChannelVoteListener.java
  src/main/java/net/javadiscord/javabot/events/ShareKnowledgeVoteListener.java
Labels: enhancement

#208 Added format-code context command
  src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java
  src/main/resources/commands/context/message.yaml
Labels: enhancement

#209 Made AutoMod exclude certain invite-links
  src/main/java/net/javadiscord/javabot/data/config/guild/ModerationConfig.java
  src/main/java/net/javadiscord/javabot/systems/moderation/AutoMod.java
Labels: enhancement

#217 Added separate Admin Role
  src/main/java/net/javadiscord/javabot/data/config/guild/ModerationConfig.java
  src/main/resources/commands/slash/staff.yaml
Labels: enhancement

#220 fix data corruption caused by duplicate commands
  src/main/java/net/javadiscord/javabot/command/InteractionHandler.java
  src/main/java/net/javadiscord/javabot/systems/staff/custom_commands/subcommands/CreateSubCommand.java
Labels: bug fix

#223 Updated README
  README.md
Labels: documentation, enhancement

#224 Fix Leaderboard Ranking
  src/main/java/net/javadiscord/javabot/systems/commands/LeaderboardCommand.java
Labels: enhancement, bug fix, feature: qotw

#219 Fixed issue with /format-code formatting bot messages
  src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java
Labels: enhancement

#225 Modal Applications
  build.gradle
  src/main/java/net/javadiscord/javabot/data/config/guild/ModerationConfig.java
  src/main/java/net/javadiscord/javabot/events/InteractionListener.java
  src/main/java/net/javadiscord/javabot/systems/help/HelpChannelInteractionManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionControlsManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionManager.java
  src/main/java/net/javadiscord/javabot/systems/staff/reaction_roles/subcommands/CreateSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/reaction_roles/subcommands/DeleteSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/SelfRoleCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/SelfRoleInteractionManager.java
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/subcommands/CreateSelfRoleSubcommand.java
  src/main/resources/commands/slash/staff.yaml
Labels: enhancement

#229 Added `/self-role enable`, `/self-role disable` & `NONE` Self Role Type
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/SelfRoleCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/subcommands/CreateSelfRoleSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/subcommands/DisableSelfRoleSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/subcommands/EnableSelfRoleSubcommand.java
  src/main/java/net/javadiscord/javabot/util/MessageActionUtils.java
  src/main/resources/commands/slash/staff.yaml
Labels: enhancement

#231 Self Role Cleanup
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/SelfRoleInteractionManager.java
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/subcommands/CreateSelfRoleSubcommand.java
Labels: enhancement
