Repository Java-Discord/JavaBot, pull requests merged in 2022-07, with the labels that each got.

#316 Changed SelfRoleInteractionManager to use Apache Commons Validator
  build.gradle.kts
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/SelfRoleInteractionManager.java
Labels: bug fix

#308 replace f*cks with hugs
  build.gradle.kts
  src/main/java/net/javadiscord/javabot/Bot.java
  src/main/java/net/javadiscord/javabot/listener/HugListener.java
  src/main/java/net/javadiscord/javabot/util/WebhookUtil.java
Labels: enhancement, new feature, needs to be tested

#320 Report Presence Message
  src/main/java/net/javadiscord/javabot/tasks/PresenceUpdater.java
Labels: enhancement

#321 User Webhook Message Links
  build.gradle.kts
  src/main/java/net/javadiscord/javabot/listener/MessageLinkListener.java
  src/main/java/net/javadiscord/javabot/util/WebhookUtil.java
Labels: enhancement

#318 Move Conversation
  README.md
  src/main/java/net/javadiscord/javabot/systems/user_commands/MoveConversationCommand.java
Labels: enhancement, review requested, new feature

#327 Removed automatic deletion of QOTW-Threads
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionControlsManager.java
Labels: bug fix, feature: qotw

#333 Fixed `/format-code` allowing String inputs
  src/main/java/net/javadiscord/javabot/systems/user_commands/format_code/FormatCodeCommand.java
Labels: bug fix
