Repository Java-Discord/JavaBot, pull requests merged in 2022-01, with the labels that each got.

#154 Added suggested message-url embed functionality
  src/main/java/net/javadiscord/javabot/Bot.java
  src/main/java/net/javadiscord/javabot/events/MessageLinkListener.java
Labels: enhancement

#155 Fixed /regex by using Google's re2j
  build.gradle
  src/main/java/net/javadiscord/javabot/systems/commands/RegexCommand.java
  src/main/resources/commands/user.yaml
Labels: bug fix

#156 Moved Custom Commands to H2 Database
  src/main/java/net/javadiscord/javabot/command/SlashCommands.java
  src/main/java/net/javadiscord/javabot/systems/commands/staff/custom_commands/CustomCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/commands/staff/custom_commands/CustomCommandList.java
  src/main/java/net/javadiscord/javabot/systems/commands/staff/custom_commands/subcommands/CustomCommandCreate.java
  src/main/java/net/javadiscord/javabot/systems/commands/staff/custom_commands/subcommands/CustomCommandDelete.java
  src/main/java/net/javadiscord/javabot/systems/commands/staff/custom_commands/subcommands/CustomCommandEdit.java
  src/main/java/net/javadiscord/javabot/systems/moderation/AutoMod.java
  src/main/java/net/javadiscord/javabot/systems/moderation/ModerationService.java
  src/main/java/net/javadiscord/javabot/systems/staff/EditEmbedCommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/EmbedCommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/QuestionCommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/SayCommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/custom_commands/CustomCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/staff/custom_commands/ListCommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/custom_commands/dao/CustomCommandRepository.java
  src/main/java/net/javadiscord/javabot/systems/staff/custom_commands/model/CustomCommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/custom_commands/subcommands/CreateSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/custom_commands/subcommands/DeleteSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/custom_commands/subcommands/EditSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/reaction_roles/ReactionRoleCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/staff/reaction_roles/subcommands/CreateReactionRole.java
  src/main/java/net/javadiscord/javabot/systems/staff/reaction_roles/subcommands/DeleteReactionRole.java
  src/main/java/net/javadiscord/javabot/systems/staff/suggestions/SuggestionCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/staff/suggestions/subcommands/AcceptSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/suggestions/subcommands/ClearSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/suggestions/subcommands/DeclineSubcommand.java
  src/main/resources/commands/staff.yaml
  src/main/resources/migrations/01-02-22_add_starboard_table.sql
  src/main/resources/schema.sql
Labels: enhancement

#157 Refactored QOTW Commands and removed usage of MongoDB
  src/main/java/net/javadiscord/javabot/events/ShareKnowledgeVoteListener.java
  src/main/java/net/javadiscord/javabot/events/SubmissionListener.java
  src/main/java/net/javadiscord/javabot/events/SuggestionListener.java
  src/main/java/net/javadiscord/javabot/systems/commands/LeaderboardCommand.java
  src/main/java/net/javadiscord/javabot/systems/commands/ProfileCommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/ClearQOTWCommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/CorrectCommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWReminderJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/dao/QuestionPointsRepository.java
  src/main/java/net/javadiscord/javabot/systems/qotw/dao/QuestionQueueRepository.java
  src/main/java/net/javadiscord/javabot/systems/qotw/model/QOTWAccount.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/QOTWCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/qotw_points/ClearSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/qotw_points/IncrementSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/qotw_points/SetSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/questions_queue/AddQuestionSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/questions_queue/ListQuestionsSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/questions_queue/RemoveQuestionSubcommand.java
  src/main/resources/commands/qotw.yaml
  src/main/resources/commands/staff.yaml
  src/main/resources/migrations/01-02-22_add_qotw_points_table.sql
  src/main/resources/schema.sql
Labels: enhancement

#158 Refactored Leaderboard Image Generation
  src/main/java/net/javadiscord/javabot/Bot.java
  src/main/java/net/javadiscord/javabot/systems/commands/LeaderboardCommand.java
  src/main/java/net/javadiscord/javabot/util/ImageCacheUtils.java
  src/main/java/net/javadiscord/javabot/util/ImageGenerationUtils.java
  src/main/resources/commands/user.yaml
  src/main/resources/images/leaderboard/LBSelfCard.png
Labels: enhancement

#161 Updated the way search results are displayed
  src/main/java/net/javadiscord/javabot/systems/commands/SearchCommand.java
Labels: enhancement

#162 Added support for Timeouts
  build.gradle
  src/main/java/net/javadiscord/javabot/data/config/guild/ModerationConfig.java
  src/main/java/net/javadiscord/javabot/systems/help/HelpChannelManager.java
  src/main/java/net/javadiscord/javabot/systems/moderation/AutoMod.java
  src/main/java/net/javadiscord/javabot/systems/moderation/ModerationService.java
  src/main/java/net/javadiscord/javabot/systems/moderation/MuteCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/MutelistCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/UnmuteCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/timeout/TimeoutCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/moderation/timeout/subcommands/AddTimeoutSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/timeout/subcommands/RemoveTimeoutSubCommand.java
  src/main/resources/commands/staff.yaml
Labels: enhancement

#164 Added missing null checks and added logging to ModerationService
  src/main/java/net/javadiscord/javabot/systems/moderation/AutoMod.java
  src/main/java/net/javadiscord/javabot/systems/moderation/BanCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/KickCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/ModerationService.java
  src/main/java/net/javadiscord/javabot/systems/moderation/timeout/subcommands/AddTimeoutSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/timeout/subcommands/RemoveTimeoutSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/subcommands/WarnAddSubCommand.java
Labels: enhancement, bug fix

#168 Refactored Submission System
  src/main/java/net/javadiscord/javabot/Bot.java
  src/main/java/net/javadiscord/javabot/data/config/guild/QOTWConfig.java
  src/main/java/net/javadiscord/javabot/events/InteractionListener.java
  src/main/java/net/javadiscord/javabot/events/SubmissionListener.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/SubmissionManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/QOTWCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/qotw_points/IncrementSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/submission/AcceptSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/submission/DeclineSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/submission/DeleteSubcommand.java
  src/main/resources/commands/qotw.yaml
Labels: enhancement

#169 Refactored Expert Questions
  src/main/java/net/javadiscord/javabot/systems/expert_questions/ExpertQuestionCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/expert_questions/ExpertSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/expert_questions/dao/ExpertQuestionRepository.java
  src/main/java/net/javadiscord/javabot/systems/expert_questions/model/ExpertQuestion.java
  src/main/java/net/javadiscord/javabot/systems/expert_questions/subcommands/AddSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/expert_questions/subcommands/ListSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/expert_questions/subcommands/RemoveSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/QuestionCommand.java
  src/main/resources/commands/staff.yaml
  src/main/resources/migrations/01-15-22_add_expert_question_table.sql
Labels: enhancement

#163 Added ID to warn embed & Doubled Warn Severities
  src/main/java/net/javadiscord/javabot/systems/moderation/ModerationService.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/model/WarnSeverity.java
Labels: enhancement

#170 Fixed a bug that was causing the bot to "spam" activity checks
  src/main/java/net/javadiscord/javabot/systems/help/HelpChannelInteractionManager.java
  src/main/java/net/javadiscord/javabot/systems/help/HelpChannelUpdater.java
Labels: bug fix, review requested

#174 Moved Starboard to H2 Database
  src/main/java/net/javadiscord/javabot/Bot.java
  src/main/java/net/javadiscord/javabot/data/config/GuildConfig.java
  src/main/java/net/javadiscord/javabot/data/config/guild/StarboardConfig.java
  src/main/java/net/javadiscord/javabot/events/StarboardListener.java
  src/main/java/net/javadiscord/javabot/events/StartupListener.java
  src/main/java/net/javadiscord/javabot/systems/jam/subcommands/admin/CancelSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/starboard/StarboardManager.java
  src/main/java/net/javadiscord/javabot/systems/starboard/dao/StarboardRepository.java
  src/main/java/net/javadiscord/javabot/systems/starboard/model/StarboardEntry.java
  src/main/resources/commands/staff.yaml
  src/main/resources/migrations/01-16-22_add_starboard_table.sql
Labels: enhancement

#175 Removed MongoDB
  build.gradle
  src/main/java/net/javadiscord/javabot/data/config/SystemsConfig.java
  src/main/java/net/javadiscord/javabot/data/mongodb/Database.java
  src/main/java/net/javadiscord/javabot/events/GuildJoinListener.java
  src/main/java/net/javadiscord/javabot/events/StartupListener.java
  src/main/java/net/javadiscord/javabot/systems/starboard/dao/StarboardRepository.java
  src/main/java/net/javadiscord/javabot/tasks/PresenceUpdater.java
Labels: enhancement

#178 Starboard Threads
  src/main/java/net/javadiscord/javabot/systems/starboard/StarboardManager.java
Labels: enhancement

#179 Starboard Threads
  src/main/java/net/javadiscord/javabot/systems/starboard/StarboardManager.java
Labels: enhancement

#193 Enhance Automod to delete links in the suggestion channel
  src/main/java/net/javadiscord/javabot/Bot.java
  src/main/java/net/javadiscord/javabot/events/SuggestionListener.java
  src/main/java/net/javadiscord/javabot/systems/moderation/AutoMod.java
Labels: enhancement

#191 Moved QOTW Submissions to H2 Database
  src/main/java/net/javadiscord/javabot/events/InteractionListener.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWCloseSubmissionsJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/SubmissionManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionControlsManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/dao/QOTWSubmissionRepository.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/model/QOTWSubmission.java
  src/main/resources/commands/staff.yaml
  src/main/resources/migrations/01-29-2021_add_submissions_table.sql
  src/main/resources/schema.sql
Labels: status: freezer, review requested, feature: qotw

#195 Added redeploy command
  src/main/java/net/javadiscord/javabot/systems/staff/RedeployCommand.java
  src/main/resources/commands/staff.yaml
Labels: new feature
