Repository Java-Discord/JavaBot, pull requests merged in 2022-08, with the labels that each got.

#335 User Preferences & QOTW Reminder
  src/main/java/net/javadiscord/javabot/Bot.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWUserReminderJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionManager.java
  src/main/java/net/javadiscord/javabot/systems/staff_commands/tags/commands/TagsCommand.java
  src/main/java/net/javadiscord/javabot/systems/user_preferences/UserPreferenceManager.java
  src/main/java/net/javadiscord/javabot/systems/user_preferences/commands/PreferencesCommand.java
  src/main/java/net/javadiscord/javabot/systems/user_preferences/commands/PreferencesListSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/user_preferences/commands/PreferencesSetSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/user_preferences/dao/UserPreferenceRepository.java
  src/main/java/net/javadiscord/javabot/systems/user_preferences/model/Preference.java
  src/main/java/net/javadiscord/javabot/systems/user_preferences/model/UserPreference.java
  src/main/java/net/javadiscord/javabot/tasks/ScheduledTasks.java
  src/main/resources/database/migrations/07-31-2022_add_user_preferences_table.sql
  src/main/resources/database/schema.sql
Labels: enhancement, new feature, feature: qotw

#337 Fixed ClosedFileSystemException in /db-admin migrate
  src/main/java/net/javadiscord/javabot/data/h2db/MigrationUtils.java
  src/main/java/net/javadiscord/javabot/data/h2db/commands/MigrateSubcommand.java
Labels: bug fix

#340 Refactored NotificationService
  src/main/java/net/javadiscord/javabot/listener/PingableNameListener.java
  src/main/java/net/javadiscord/javabot/listener/StateListener.java
  src/main/java/net/javadiscord/javabot/systems/moderation/AutoMod.java
  src/main/java/net/javadiscord/javabot/systems/moderation/ModerationService.java
  src/main/java/net/javadiscord/javabot/systems/moderation/server_lock/ServerLockManager.java
  src/main/java/net/javadiscord/javabot/systems/notification/GuildNotificationService.java
  src/main/java/net/javadiscord/javabot/systems/notification/NotificationService.java
  src/main/java/net/javadiscord/javabot/systems/notification/QOTWGuildNotificationService.java
  src/main/java/net/javadiscord/javabot/systems/notification/QOTWNotificationService.java
  src/main/java/net/javadiscord/javabot/systems/notification/UserNotificationService.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWReminderJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/commands/qotw_points/IncrementPointsSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionControlsManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/subcommands/MarkBestAnswerSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff_commands/self_roles/ChangeSelfRoleStatusSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff_commands/self_roles/CreateSelfRoleSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff_commands/self_roles/RemoveSelfRolesSubcommand.java
Labels: enhancement

#342 Moved /help-guidelines and /help-ping to /help
  src/main/java/net/javadiscord/javabot/systems/help/commands/HelpCommand.java
  src/main/java/net/javadiscord/javabot/systems/help/commands/subcommands/HelpGuidelinesCommand.java
  src/main/java/net/javadiscord/javabot/systems/help/commands/subcommands/HelpPingCommand.java
Labels: enhancement, feature: help-system

#347 Reworked the Help Overview Embed
  src/main/java/net/javadiscord/javabot/data/config/guild/HelpConfig.java
  src/main/java/net/javadiscord/javabot/systems/help/HelpChannelUpdater.java
  src/main/java/net/javadiscord/javabot/util/StringUtils.java
  src/main/resources/help_guidelines/guidelines_text.txt
  src/main/resources/help_overview/overview_image_url.txt
Labels: enhancement, feature: help-system

#349 Added `guilds/{guild_id}/leaderboard/experience` and paginated QOTW-Leaderboard route
  README.md
  src/main/java/net/javadiscord/javabot/api/routes/data/UserData.java
  src/main/java/net/javadiscord/javabot/api/routes/leaderboard/help_experience/HelpExperienceLeaderboardController.java
  src/main/java/net/javadiscord/javabot/api/routes/leaderboard/help_experience/model/ExperienceUserData.java
  src/main/java/net/javadiscord/javabot/api/routes/leaderboard/qotw/QOTWLeaderboardController.java
  src/main/java/net/javadiscord/javabot/api/routes/leaderboard/qotw/model/QOTWUserData.java
  src/main/java/net/javadiscord/javabot/api/routes/metrics/MetricsController.java
  src/main/java/net/javadiscord/javabot/api/routes/qotw_leaderboard/model/QOTWMemberData.java
  src/main/java/net/javadiscord/javabot/api/routes/user_profile/UserProfileController.java
  src/main/java/net/javadiscord/javabot/systems/help/HelpExperienceService.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWPointsService.java
  src/main/java/net/javadiscord/javabot/systems/qotw/dao/QuestionPointsRepository.java
Labels: feature: api

#334 Fixed Message Cache Primary Key Violation
  src/main/java/net/javadiscord/javabot/data/h2db/message_cache/dao/MessageCacheRepository.java
Labels: bug fix

#355 Fixed NPE when using `/help account`
  src/main/java/net/javadiscord/javabot/systems/help/commands/HelpAccountSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/help/model/HelpAccount.java
Labels: bug fix

#357 Added missing option to `/db-admin` and migration to drop unused tables
  src/main/java/net/javadiscord/javabot/data/h2db/commands/ExportTableSubcommand.java
  src/main/resources/database/migrations/08-13-2022_remove_unused_tables.sql
Labels: enhancement
