Repository Java-Discord/JavaBot, pull requests merged in 2022-04, with the labels that each got.

#249 Better Autocomplete
  src/main/java/net/javadiscord/javabot/data/h2db/commands/DbAdminCommandHandler.java
  src/main/java/net/javadiscord/javabot/data/h2db/commands/MigrateSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/jam/JamAdminCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/jam/subcommands/admin/RemoveSubmissionsSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/jam/subcommands/admin/RemoveThemeSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/QOTWCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/questions_queue/RemoveQuestionSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/custom_commands/CustomCommandHandler.java
  src/main/java/net/javadiscord/javabot/util/AutocompleteUtils.java
Labels: enhancement, bug fix

#250 GitHub Links
  src/main/java/net/javadiscord/javabot/Bot.java
  src/main/java/net/javadiscord/javabot/listener/GitHubLinkListener.java
  src/main/java/net/javadiscord/javabot/util/StringUtils.java
Labels: new feature

#253 Best Answer Functionality
  src/main/java/net/javadiscord/javabot/listener/InteractionListener.java
  src/main/java/net/javadiscord/javabot/listener/SuggestionListener.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWCloseSubmissionsJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/QOTWCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/qotw_points/IncrementSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionControlsManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionInteractionManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/dao/QOTWSubmissionRepository.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/subcommands/MarkBestAnswerSubcommand.java
  src/main/java/net/javadiscord/javabot/util/MessageActionUtils.java
  src/main/resources/commands/slash/qotw.yaml
Labels: new feature, feature: qotw, suggestion

#256 Fixed /report in threads
  src/main/java/net/javadiscord/javabot/systems/moderation/ReportCommand.java
Labels: bug fix

#255 Help Channel Experience
  src/main/java/net/javadiscord/javabot/data/config/BotConfig.java
  src/main/java/net/javadiscord/javabot/data/config/guild/HelpConfig.java
  src/main/java/net/javadiscord/javabot/systems/help/HelpChannelInteractionManager.java
  src/main/java/net/javadiscord/javabot/systems/help/HelpChannelListener.java
  src/main/java/net/javadiscord/javabot/systems/help/HelpChannelManager.java
  src/main/java/net/javadiscord/javabot/systems/help/HelpExperienceJob.java
  src/main/java/net/javadiscord/javabot/systems/help/HelpExperienceService.java
  src/main/java/net/javadiscord/javabot/systems/help/ThanksCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/help/commands/HelpCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/help/commands/HelpGuidelinesCommand.java
  src/main/java/net/javadiscord/javabot/systems/help/commands/HelpPingCommand.java
  src/main/java/net/javadiscord/javabot/systems/help/commands/UnreserveCommand.java
  src/main/java/net/javadiscord/javabot/systems/help/commands/subcommands/HelpAccountSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/help/commands/subcommands/ThanksLeaderboardSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/help/dao/HelpAccountRepository.java
  src/main/java/net/javadiscord/javabot/systems/help/dao/HelpTransactionRepository.java
  src/main/java/net/javadiscord/javabot/systems/help/model/HelpAccount.java
  src/main/java/net/javadiscord/javabot/systems/help/model/HelpTransaction.java
  src/main/java/net/javadiscord/javabot/systems/help/model/HelpTransactionMessage.java
  src/main/java/net/javadiscord/javabot/systems/help/naming_strategies/AlphabetNamingStrategy.java
  src/main/java/net/javadiscord/javabot/systems/help/naming_strategies/AnimalNamingStrategy.java
  src/main/java/net/javadiscord/javabot/systems/help/naming_strategies/ChannelNamingStrategy.java
  src/main/java/net/javadiscord/javabot/systems/help/naming_strategies/CoffeeNamingStrategy.java
  src/main/java/net/javadiscord/javabot/systems/help/naming_strategies/GreekAlphabetNamingStrategy.java
  src/main/java/net/javadiscord/javabot/tasks/ScheduledTasks.java
  src/main/java/net/javadiscord/javabot/util/StringUtils.java
  src/main/resources/commands/slash/help.yaml
  src/main/resources/commands/slash/staff.yaml
  src/main/resources/economy/sql/find_latest_transactions.sql
  src/main/resources/migrations/04-13-2022_add_help_xp_tables.sql
  src/main/resources/schema.sql
Labels: feature: help-system, new feature

#248 Message Cache
  src/main/java/net/javadiscord/javabot/Bot.java
  src/main/java/net/javadiscord/javabot/data/config/GuildConfig.java
  src/main/java/net/javadiscord/javabot/data/config/guild/MessageCacheConfig.java
  src/main/java/net/javadiscord/javabot/data/h2db/DbActions.java
  src/main/java/net/javadiscord/javabot/data/h2db/commands/DbAdminCommandHandler.java
  src/main/java/net/javadiscord/javabot/data/h2db/commands/message_cache/MessageCacheInfoSubcommand.java
  src/main/java/net/javadiscord/javabot/data/h2db/message_cache/MessageCache.java
  src/main/java/net/javadiscord/javabot/data/h2db/message_cache/dao/MessageCacheRepository.java
  src/main/java/net/javadiscord/javabot/data/h2db/message_cache/model/CachedMessage.java
  src/main/java/net/javadiscord/javabot/systems/commands/IdCalculatorCommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/RedeployCommand.java
  src/main/java/net/javadiscord/javabot/util/GuildUtils.java
  src/main/resources/commands/slash/staff.yaml
  src/main/resources/migrations/04-02-2022_add_message_cache_table.sql
  src/main/resources/schema.sql
Labels: enhancement, new feature

#262 Further Message Cache Improvements
  src/main/java/net/javadiscord/javabot/Bot.java
  src/main/java/net/javadiscord/javabot/data/h2db/commands/DbAdminCommandHandler.java
  src/main/java/net/javadiscord/javabot/data/h2db/commands/message_cache/MessageCacheInfoSubcommand.java
  src/main/java/net/javadiscord/javabot/data/h2db/message_cache/MessageCache.java
  src/main/java/net/javadiscord/javabot/data/h2db/message_cache/MessageCacheListener.java
  src/main/java/net/javadiscord/javabot/systems/help/dao/HelpTransactionRepository.java
  src/main/java/net/javadiscord/javabot/systems/help/model/HelpAccount.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/subcommands/MarkBestAnswerSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/suggestions/SuggestionSubcommand.java
Labels: enhancement

#263 Fixed and Improved `/purge`
  src/main/java/net/javadiscord/javabot/systems/moderation/PurgeCommand.java
  src/main/resources/commands/slash/staff.yaml
Labels: enhancement, bug fix

#264 Improve QOTW Submission Handling & NotificationService
  src/main/java/net/javadiscord/javabot/command/InteractionHandler.java
  src/main/java/net/javadiscord/javabot/data/h2db/message_cache/MessageCache.java
  src/main/java/net/javadiscord/javabot/listener/StartupListener.java
  src/main/java/net/javadiscord/javabot/systems/commands/LeaderboardCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/AutoMod.java
  src/main/java/net/javadiscord/javabot/systems/moderation/ServerLock.java
  src/main/java/net/javadiscord/javabot/systems/notification/GuildNotificationService.java
  src/main/java/net/javadiscord/javabot/systems/notification/NotificationService.java
  src/main/java/net/javadiscord/javabot/systems/notification/QOTWNotificationService.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWCloseSubmissionsJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/QOTWReminderJob.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/qotw_points/IncrementSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionControlsManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionInteractionManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionStatus.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/dao/QOTWSubmissionRepository.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/model/QOTWSubmission.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/subcommands/MarkBestAnswerSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/subcommands/CreateSelfRoleSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/subcommands/DisableSelfRoleSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/subcommands/EnableSelfRoleSubcommand.java
  src/main/java/net/javadiscord/javabot/util/GuildUtils.java
  src/main/resources/migrations/04-18-2022_update_qotw_table.sql
  src/main/resources/schema.sql
Labels: enhancement, feature: qotw

#265 Bumped JDA to latest version `(5492a76)`
  build.gradle
  src/main/java/net/javadiscord/javabot/command/DelegatingCommandHandler.java
  src/main/java/net/javadiscord/javabot/command/interfaces/MessageContextCommand.java
  src/main/java/net/javadiscord/javabot/command/interfaces/SlashCommand.java
  src/main/java/net/javadiscord/javabot/command/interfaces/UserContextCommand.java
  src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/ReportCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/WarnsCommand.java
  src/main/java/net/javadiscord/javabot/systems/staff/self_roles/SelfRoleCommandHandler.java
Labels: enhancement

#267 Made `/qotw questions-queue add` use Modals to support multi-line text input
  src/main/java/net/javadiscord/javabot/listener/InteractionListener.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/QOTWSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/questions_queue/AddQuestionSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/questions_queue/ListQuestionsSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/questions_queue/RemoveQuestionSubcommand.java
  src/main/resources/commands/slash/qotw.yaml
Labels: enhancement, feature: qotw

#266 Experience Leaderboard
  src/main/java/net/javadiscord/javabot/listener/InteractionListener.java
  src/main/java/net/javadiscord/javabot/systems/help/HelpExperienceService.java
  src/main/java/net/javadiscord/javabot/systems/help/commands/HelpCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/help/commands/subcommands/ExperienceLeaderboardSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/help/commands/subcommands/HelpAccountSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/help/dao/HelpAccountRepository.java
  src/main/java/net/javadiscord/javabot/systems/help/model/HelpAccount.java
  src/main/resources/commands/slash/help.yaml
Labels: new feature, feature: qotw

#269 Added linux distro to /botinfo
  src/main/java/net/javadiscord/javabot/systems/commands/BotInfoCommand.java
Labels: enhancement
