Repository Java-Discord/JavaBot, pull requests merged in 2022-05, with the labels that each got.

#272 Further Improve QOTW Submissions
  src/main/java/net/javadiscord/javabot/systems/notification/QOTWNotificationService.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionControlsManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionManager.java
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/subcommands/MarkBestAnswerSubcommand.java
Labels: enhancement, bug fix, feature: qotw

#275 Moved leaderboards to single command
  src/main/java/net/javadiscord/javabot/listener/InteractionListener.java
  src/main/java/net/javadiscord/javabot/systems/commands/LeaderboardCommand.java
  src/main/java/net/javadiscord/javabot/systems/commands/ProfileCommand.java
  src/main/java/net/javadiscord/javabot/systems/commands/subcommands/leaderboard/ExperienceLeaderboardSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/commands/subcommands/leaderboard/QOTWLeaderboardSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/commands/subcommands/leaderboard/ThanksLeaderboardSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/help/commands/HelpCommandHandler.java
  src/main/java/net/javadiscord/javabot/systems/qotw/subcommands/qotw_points/IncrementSubcommand.java
  src/main/resources/commands/slash/help.yaml
  src/main/resources/commands/slash/user.yaml
Labels: enhancement

#280 Added name check and change system
  src/main/java/net/javadiscord/javabot/Bot.java
  src/main/java/net/javadiscord/javabot/data/h2db/message_cache/MessageCacheListener.java
  src/main/java/net/javadiscord/javabot/listener/PingableNameListener.java
  src/main/java/net/javadiscord/javabot/util/StringUtils.java
Labels: new feature

#286 Upgraded to JDA v5.0.0-alpha.12
  build.gradle.kts
  src/main/java/net/javadiscord/javabot/systems/moderation/AutoMod.java
Labels: enhancement

#294 Fix QOTW
  src/main/java/net/javadiscord/javabot/systems/qotw/submissions/SubmissionControlsManager.java
  src/main/resources/migrations/05-09-2022_fix_qotw_submissions.sql
  src/main/resources/migrations/05-30-2022_fix_qotw_submissions.sql
Labels: bug fix
