Repository Java-Discord/JavaBot, pull requests merged in 2022-03, with the labels that each got.

#222 Moderation Abstract classes and implementations
  src/main/java/net/javadiscord/javabot/command/moderation/ModerateCommand.java
  src/main/java/net/javadiscord/javabot/command/moderation/ModerateUserCommand.java
  src/main/java/net/javadiscord/javabot/data/config/GuildConfig.java
  src/main/java/net/javadiscord/javabot/systems/moderation/AutoMod.java
  src/main/java/net/javadiscord/javabot/systems/moderation/BanCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/KickCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/PruneCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/PurgeCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/ReportCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/UnbanCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/subcommands/DiscardAllWarnsSubcommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/subcommands/DiscardWarnByIdSubCommand.java
  src/main/java/net/javadiscord/javabot/systems/moderation/warn/subcommands/WarnAddSubcommand.java
Labels: enhancement

#235 Refactored Report Messages to use Threads
  checkstyle/checkstyle.xml
  src/main/java/net/javadiscord/javabot/events/InteractionListener.java
  src/main/java/net/javadiscord/javabot/systems/moderation/ModerationService.java
  src/main/java/net/javadiscord/javabot/systems/moderation/ReportCommand.java
Labels: enhancement

#240 Added Available Help-Channels to /help-guidelines
  src/main/java/net/javadiscord/javabot/systems/help/HelpGuidelinesCommandHandler.java
Labels: enhancement, feature: help-system

#244 Option Autocomplete
  src/main/java/net/javadiscord/javabot/command/data/slash_commands/SlashCommandConfig.java
  src/main/java/net/javadiscord/javabot/command/data/slash_commands/SlashOptionConfig.java
Labels: enhancement, new feature
